#!/bin/bash

# ============================================================================
# SCRIPT COMPLETO PARA APLICAR LA CONFIGURACIÓN CORREGIDA
# ============================================================================

echo "🔄 APLICANDO CONFIGURACIÓN CORREGIDA EN EL SERVIDOR VPS"
echo ""

echo "📋 CAMBIOS PRINCIPALES:"
echo "✅ Eliminar variables inexistentes: GOTRUE_EXTERNAL_REDIRECT_ENABLED, GOTRUE_MAILER_AUTOCONFIRM_REDIRECTS"
echo "✅ Configurar ADDITIONAL_REDIRECT_URLS correctamente"
echo "✅ Asegurar MAILER_URLPATHS_RECOVERY=/auth/reset-password"
echo ""

echo "🚀 COMANDOS PARA EL SERVIDOR:"
echo ""
echo "1. Conectar al servidor VPS:"
echo "   ssh root@tu-servidor-ip"
echo ""
echo "2. Ir al directorio correcto:"
echo "   cd ~/supabase-automated-self-host/docker"
echo ""
echo "3. Hacer backup del .env actual:"
echo "   cp .env .env.backup-\$(date +%Y%m%d-%H%M%S)"
echo ""
echo "4. Aplicar la nueva configuración:"
echo "   # Opción 1: Editar manualmente"
echo "   nano .env"
echo ""
echo "   # Opción 2: Descargar el archivo corregido"
echo "   wget -O .env https://raw.githubusercontent.com/tuusuario/tu-repo/main/server-env-corrected.env"
echo ""
echo "5. Verificar los cambios importantes:"
echo "   grep -E 'SITE_URL|ADDITIONAL_REDIRECT_URLS|MAILER_URLPATHS_RECOVERY' .env"
echo ""
echo "6. Reiniciar servicios de Supabase:"
echo "   docker-compose down"
echo "   docker-compose up -d"
echo ""
echo "7. Verificar que todos los servicios estén funcionando:"
echo "   docker-compose ps"
echo ""
echo "8. Verificar logs del servicio auth:"
echo "   docker logs supabase-auth --tail 20"
echo ""
echo "9. Probar el reset de contraseña:"
echo "   curl -X POST \"https://supabase.lacasadelsueloradianteapp.com/auth/v1/recover\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -H \"apikey: \$ANON_KEY\" \\"
echo "     -d '{\"email\": \"djmartiiservicios@gmail.com\"}'"
echo ""

echo "📧 LA CONFIGURACIÓN CORRECTA DEBE INCLUIR:"
echo ""
echo "SITE_URL=https://lacasadelsueloradiante.es"
echo "ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**,https://lacasadelsueloradiante.es/auth/**,https://lacasadelsueloradiante.es/auth/reset-password"
echo "MAILER_URLPATHS_RECOVERY=/auth/reset-password"
echo ""
echo "Y NO DEBE INCLUIR:"
echo "❌ GOTRUE_EXTERNAL_REDIRECT_ENABLED"
echo "❌ GOTRUE_MAILER_AUTOCONFIRM_REDIRECTS"
echo ""

echo "🔍 VERIFICAR FUNCIONAMIENTO:"
echo ""
echo "1. Los emails de reset deberían llegar con URL:"
echo "   https://lacasadelsueloradiante.es/auth/reset-password?token=xxx"
echo ""
echo "2. El token debería ser válido y funcionar en tu aplicación"
echo ""
echo "3. Si aún no funciona, revisar logs:"
echo "   docker logs supabase-auth | grep -i 'recovery\\|reset\\|email'"