# Docker Compose para Nginx con Certbot (Proxy Reverso y SSL)
# Uso: docker-compose -f docker-compose-nginx.yml up -d

version: "3.9"

services:
  nginx:
    container_name: nginx-container
    image: jonasal/nginx-certbot:6.0.1-nginx1.29.1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/user_conf.d       # Configuración Nginx
      - ./certbot/www:/var/www/certbot        # Webroot para Certbot
      - ./certbot/conf:/etc/letsencrypt       # Certificados persistentes
    environment:
      # Variables para certbot (opcional, se pueden pasar como argumentos)
      - CERTBOT_EMAIL=javipablo0408@gmail.com  # Cambiar por tu email
      - DHPARAM_SIZE=2048
      - RSA_KEY_SIZE=2048
      - ELLIPTIC_CURVE=secp256r1
      - STAGING=0                              # 0 = producción, 1 = testing
    networks:
      - lacasadelsueloradiante_network
    labels:
      - "traefik.enable=false"  # Si usas Traefik, deshabilitarlo aquí

networks:
  lacasadelsueloradiante_network:
    external: true