#!/bin/bash

# ============================================================================
# SCRIPT DE IMPLEMENTACIÓN PASO A PASO
# Ejecutar cada sección una por una
# ============================================================================

echo "🚀 IMPLEMENTACIÓN COMPLETA - PASO A PASO"
echo ""

echo "==========================================================================="
echo "📋 PASO 1: VERIFICAR QUE LA PLANTILLA SEA ACCESIBLE"
echo "==========================================================================="
echo ""
echo "Antes de configurar el servidor, verifica que tu plantilla esté online:"
echo ""
echo "curl -I https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo ""
echo "✅ Debe devolver: HTTP/2 200"
echo "❌ Si devuelve 404, primero haz deploy de tu aplicación Next.js"
echo ""
echo "Presiona ENTER cuando la plantilla esté accesible..."
read -r

echo "==========================================================================="
echo "🔧 PASO 2: CONECTAR AL SERVIDOR Y HACER BACKUP"
echo "==========================================================================="
echo ""
echo "Ejecuta estos comandos:"
echo ""
echo "ssh root@tu-servidor-ip"
echo ""
echo "Una vez conectado al servidor, ejecuta:"
echo ""
echo "cd ~/supabase-automated-self-host/docker"
echo "pwd  # Verifica que estés en el directorio correcto"
echo "ls -la .env  # Verifica que el archivo .env existe"
echo ""
echo "# Hacer backup del .env actual"
echo "cp .env .env.backup-\$(date +%Y%m%d-%H%M%S)"
echo "ls -la .env*  # Verifica que el backup se creó"
echo ""
echo "Presiona ENTER cuando hayas hecho el backup..."
read -r

echo "==========================================================================="
echo "📝 PASO 3: EDITAR EL ARCHIVO .ENV"
echo "==========================================================================="
echo ""
echo "En el servidor, ejecuta:"
echo ""
echo "nano .env"
echo ""
echo "🔍 BUSCAR Y ELIMINAR estas líneas (si existen):"
echo ""
echo "❌ GOTRUE_EXTERNAL_REDIRECT_ENABLED=true"
echo "❌ GOTRUE_MAILER_AUTOCONFIRM_REDIRECTS=true"
echo ""
echo "✅ BUSCAR Y VERIFICAR/AÑADIR estas líneas:"
echo ""
echo "SITE_URL=https://lacasadelsueloradiante.es"
echo "MAILER_URLPATHS_RECOVERY=/auth/reset-password"
echo "ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**,https://lacasadelsueloradiante.es/auth/**,https://lacasadelsueloradiante.es/auth/reset-password"
echo ""
echo "✅ AÑADIR esta línea nueva (plantilla personalizada):"
echo ""
echo "MAILER_TEMPLATES_RECOVERY=https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo ""
echo "✅ OPCIONAL - Añadir sujeto personalizado:"
echo ""
echo "MAILER_SUBJECTS_RECOVERY=Recupera tu contraseña - La Casa del Suelo Radiante"
echo ""
echo "💾 Guardar con: Ctrl+O, Enter, Ctrl+X"
echo ""
echo "Presiona ENTER cuando hayas editado el .env..."
read -r

echo "==========================================================================="
echo "🔍 PASO 4: VERIFICAR LA CONFIGURACIÓN"
echo "==========================================================================="
echo ""
echo "En el servidor, verifica que los cambios se guardaron correctamente:"
echo ""
echo "grep -E 'SITE_URL|MAILER.*RECOVERY|ADDITIONAL_REDIRECT|GOTRUE_EXTERNAL' .env"
echo ""
echo "✅ Deberías ver algo como:"
echo "SITE_URL=https://lacasadelsueloradiante.es"
echo "MAILER_URLPATHS_RECOVERY=/auth/reset-password"
echo "MAILER_TEMPLATES_RECOVERY=https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo "MAILER_SUBJECTS_RECOVERY=Recupera tu contraseña - La Casa del Suelo Radiante"
echo "ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**,..."
echo ""
echo "❌ NO deberías ver:"
echo "GOTRUE_EXTERNAL_REDIRECT_ENABLED"
echo "GOTRUE_MAILER_AUTOCONFIRM_REDIRECTS"
echo ""
echo "Presiona ENTER cuando hayas verificado la configuración..."
read -r

echo "==========================================================================="
echo "🔄 PASO 5: REINICIAR EL SERVICIO AUTH"
echo "==========================================================================="
echo ""
echo "En el servidor:"
echo ""
echo "# Ver servicios actuales"
echo "docker-compose ps"
echo ""
echo "# Reiniciar solo el servicio auth (más rápido)"
echo "docker-compose restart auth"
echo ""
echo "# Verificar que esté funcionando"
echo "docker-compose ps | grep auth"
echo "docker logs supabase-auth --tail 10"
echo ""
echo "✅ El servicio 'supabase-auth' debería estar 'Up' y sin errores en los logs"
echo ""
echo "Presiona ENTER cuando el servicio esté funcionando..."
read -r

echo "==========================================================================="
echo "🧪 PASO 6: PROBAR EL RESET PASSWORD"
echo "==========================================================================="
echo ""
echo "Desde el servidor o tu máquina local, ejecuta:"
echo ""
echo "curl -X POST \"https://supabase.lacasadelsueloradianteapp.com/auth/v1/recover\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"apikey: eyJ0eXAiOiAiSldUIiwiYWxnIjogIkhTMjU2In0.ewogICJyb2xlIjogImFub24iLAogICJpc3MiOiAic3VwYWJhc2UiLAogICJpYXQiOiAxNzU4NzAwNTMzLAogICJleHAiOiAxOTE2MzgwNTMzCn0.uhOFMEExih6oXgd9tDGK87L-xQMK6J-6w5oPDs2tnbc\" \\"
echo "  -d '{\"email\": \"djmartiiservicios@gmail.com\"}'"
echo ""
echo "✅ Debería devolver algo como: {}"
echo "✅ El email debería llegar en 1-2 minutos"
echo ""
echo "Presiona ENTER cuando hayas enviado la petición..."
read -r

echo "==========================================================================="
echo "📧 PASO 7: VERIFICAR EL EMAIL RECIBIDO"
echo "==========================================================================="
echo ""
echo "Revisa el email en djmartiiservicios@gmail.com"
echo ""
echo "✅ El email debería tener:"
echo "   - Sujeto: 'Recupera tu contraseña - La Casa del Suelo Radiante'"
echo "   - Diseño personalizado con tu branding"
echo "   - Botón que apunte a: https://lacasadelsueloradiante.es/auth/reset-password?token=xxx"
echo ""
echo "❌ Si el email no llega o tiene problemas:"
echo "   1. Revisar logs: docker logs supabase-auth | grep -i recovery"
echo "   2. Verificar plantilla: curl https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo "   3. Verificar SMTP: docker logs supabase-auth | grep -i smtp"
echo ""

echo "==========================================================================="
echo "🎯 RESUMEN DE LO QUE HICIMOS"
echo "==========================================================================="
echo ""
echo "📁 Archivos modificados en el servidor:"
echo "   - /root/supabase-automated-self-host/docker/.env"
echo ""
echo "🔧 Configuración añadida:"
echo "   - MAILER_TEMPLATES_RECOVERY=https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo "   - MAILER_SUBJECTS_RECOVERY=Recupera tu contraseña - La Casa del Suelo Radiante"
echo "   - Eliminadas variables inexistentes"
echo ""
echo "🎨 Plantilla HTML:"
echo "   - Servida desde: https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo "   - Con diseño personalizado de tu empresa"
echo ""
echo "🔗 Resultado:"
echo "   - Emails con plantilla personalizada"
echo "   - Links que apuntan a tu web: https://lacasadelsueloradiante.es/auth/reset-password"
echo ""
echo "¡IMPLEMENTACIÓN COMPLETADA! 🎉"