#!/bin/bash

# ============================================================================
# IMPLEMENTAR PLANTILLA HTML PERSONALIZADA PARA RESET PASSWORD
# ============================================================================

echo "🎨 IMPLEMENTANDO PLANTILLA HTML PERSONALIZADA PARA RESET"
echo ""

echo "📋 PASOS PARA IMPLEMENTAR:"
echo ""

echo "1️⃣  SUBIR LA PLANTILLA A TU WEB:"
echo ""
echo "# Crear directorio en tu aplicación Next.js:"
echo "mkdir -p public/templates"
echo ""
echo "# La plantilla ya está creada en: public/templates/recovery-email.html"
echo "# Asegúrate de que esté accesible en:"
echo "# https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo ""

echo "2️⃣  VERIFICAR QUE LA PLANTILLA SEA ACCESIBLE:"
echo ""
echo "# Desde tu máquina local, verificar que la plantilla se sirve:"
echo "curl -I https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo ""
echo "# Debería devolver: HTTP/2 200"
echo ""

echo "3️⃣  CONFIGURAR EL .ENV EN EL SERVIDOR VPS:"
echo ""
echo "ssh root@tu-servidor-ip"
echo "cd ~/supabase-automated-self-host/docker"
echo ""
echo "# Hacer backup"
echo "cp .env .env.backup-template-\$(date +%Y%m%d-%H%M%S)"
echo ""
echo "# Editar .env y añadir/modificar estas líneas:"
echo "nano .env"
echo ""

echo "📝 CONFIGURACIÓN PARA EL .ENV DEL SERVIDOR:"
echo ""
echo "# ✅ CONFIGURACIÓN BÁSICA (verificar que esté correcto)"
echo "SITE_URL=https://lacasadelsueloradiante.es"
echo "MAILER_URLPATHS_RECOVERY=/auth/reset-password"
echo "ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**,https://lacasadelsueloradiante.es/auth/**"
echo ""
echo "# ✅ PLANTILLA HTML PERSONALIZADA (añadir esta línea)"
echo "MAILER_TEMPLATES_RECOVERY=https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo ""
echo "# ✅ SUJETO PERSONALIZADO (opcional)"
echo "MAILER_SUBJECTS_RECOVERY=Recupera tu contraseña - La Casa del Suelo Radiante"
echo ""
echo "# ❌ ELIMINAR estas líneas si existen (NO son válidas)"
echo "# GOTRUE_EXTERNAL_REDIRECT_ENABLED=true"
echo "# GOTRUE_MAILER_AUTOCONFIRM_REDIRECTS=true"
echo ""

echo "4️⃣  REINICIAR EL SERVICIO AUTH:"
echo ""
echo "# Solo reiniciar el servicio auth (más rápido)"
echo "docker-compose restart auth"
echo ""
echo "# Verificar que esté funcionando"
echo "docker logs supabase-auth --tail 10"
echo ""

echo "5️⃣  PROBAR EL RESET CON PLANTILLA:"
echo ""
echo "# Probar desde el servidor o tu máquina local:"
echo "curl -X POST \"https://supabase.lacasadelsueloradianteapp.com/auth/v1/recover\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -H \"apikey: \${ANON_KEY}\" \\"
echo "  -d '{\"email\": \"djmartiiservicios@gmail.com\"}'"
echo ""

echo "6️⃣  VERIFICAR EL EMAIL RECIBIDO:"
echo ""
echo "✅ El email debería usar tu plantilla HTML personalizada"
echo "✅ El botón debería apuntar a: https://lacasadelsueloradiante.es/auth/reset-password?token=xxx"
echo "✅ Debería tener el diseño de tu empresa"
echo ""

echo "🔍 TROUBLESHOOTING:"
echo ""
echo "Si la plantilla no se usa:"
echo ""
echo "1. Verificar que la URL de la plantilla sea accesible:"
echo "   curl https://lacasadelsueloradiante.es/templates/recovery-email.html"
echo ""
echo "2. Verificar logs de auth:"
echo "   docker logs supabase-auth | grep -i template"
echo ""
echo "3. Verificar configuración actual:"
echo "   grep MAILER_TEMPLATES_RECOVERY .env"
echo ""
echo "4. Si hay errores, usar plantilla por defecto temporalmente:"
echo "   MAILER_TEMPLATES_RECOVERY="
echo ""

echo "🎯 CÓMO FUNCIONA:"
echo ""
echo "1. GoTrue lee MAILER_TEMPLATES_RECOVERY del .env"
echo "2. Descarga la plantilla HTML desde tu web"
echo "3. Reemplaza {{ .ConfirmationURL }}, {{ .Email }}, {{ .SiteURL }}"
echo "4. Envía el email con tu plantilla personalizada"
echo "5. El link apunta a SITE_URL + MAILER_URLPATHS_RECOVERY + token"
echo ""

echo "📧 RESULTADO FINAL:"
echo "   Email con diseño personalizado"
echo "   Link: https://lacasadelsueloradiante.es/auth/reset-password?token=xxx&type=recovery"
echo "   Sujeto: Recupera tu contraseña - La Casa del Suelo Radiante"