#!/bin/bash

# ============================================================================
# VERIFICACIÓN COMPLETA: redirectTo CONFIGURADO CORRECTAMENTE
# ============================================================================

echo "✅ CONFIGURACIÓN DE redirectTo VERIFICADA Y CORREGIDA"
echo ""

echo "========================================================================="
echo "📧 CONFIGURACIÓN EN EL CLIENTE (API)"
echo "========================================================================="
echo ""
echo "📁 Archivo: src/app/api/send-reset-email/route.ts"
echo ""
echo "✅ CORREGIDO - Ahora usa dominio fijo:"
echo ""
echo "await supabase.auth.resetPasswordForEmail(email, {"
echo "  redirectTo: 'https://lacasadelsueloradiante.es/auth/reset-password'"
echo "})"
echo ""
echo "🔄 Antes usaba: \${process.env.NEXT_PUBLIC_SITE_URL}/auth/reset-password"
echo "✅ Ahora usa: https://lacasadelsueloradiante.es/auth/reset-password"
echo ""

echo "========================================================================="
echo "⚙️ CONFIGURACIÓN EN EL SERVIDOR SUPABASE"
echo "========================================================================="
echo ""
echo "📁 Archivo: server-env-with-template.env (para copiar al servidor)"
echo ""
echo "✅ Variables críticas:"
echo ""
echo "SITE_URL=https://lacasadelsueloradiante.es"
echo "MAILER_URLPATHS_RECOVERY=/auth/reset-password"
echo "ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**,https://lacasadelsueloradiante.es/auth/**"
echo ""
echo "🎯 Esto asegura que:"
echo "1. Supabase acepta redirectTo de tu dominio"
echo "2. Los emails generados apunten a tu web"
echo "3. Los tokens sean válidos para tu aplicación"
echo ""

echo "========================================================================="
echo "🖥️ HANDLER EN EL FRONTEND"
echo "========================================================================="
echo ""
echo "📁 Archivo: src/app/auth/reset-password/page.tsx"
echo ""
echo "✅ Maneja dos tipos de tokens que puede enviar Supabase:"
echo ""
echo "1. TOKENS MODERNOS:"
echo "   ?access_token=xxx&refresh_token=yyy"
echo ""
echo "2. TOKENS PKCE:"
echo "   ?token=xxx&type=recovery"
echo ""
echo "✅ Flujos de actualización de contraseña:"
echo ""
echo "• Tokens modernos: page.tsx → /api/reset-password → supabase.auth.updateUser()"
echo "• Tokens PKCE: page.tsx → supabase.auth.updateUser() directamente"
echo ""

echo "========================================================================="
echo "🚀 PRÓXIMOS PASOS PARA IMPLEMENTAR"
echo "========================================================================="
echo ""
echo "1️⃣ HACER DEPLOY DE LA APLICACIÓN:"
echo ""
echo "# Hacer commit de los cambios"
echo "git add ."
echo "git commit -m 'Fix redirectTo configuration for password reset'"
echo "git push"
echo ""
echo "# Hacer deploy (ejemplo con tu método actual)"
echo "# docker build, docker push, etc."
echo ""

echo "2️⃣ CONFIGURAR EL SERVIDOR SUPABASE:"
echo ""
echo "ssh root@tu-servidor"
echo "cd ~/supabase-automated-self-host/docker"
echo ""
echo "# Verificar configuración actual"
echo "grep -E 'SITE_URL|MAILER.*RECOVERY|ADDITIONAL_REDIRECT' .env"
echo ""
echo "# Si no está correcto, editar:"
echo "nano .env"
echo ""
echo "# Añadir/verificar estas líneas:"
echo "SITE_URL=https://lacasadelsueloradiante.es"
echo "MAILER_URLPATHS_RECOVERY=/auth/reset-password"
echo "ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**,https://lacasadelsueloradiante.es/auth/**"
echo ""
echo "# Reiniciar auth"
echo "docker-compose restart auth"
echo ""

echo "3️⃣ PROBAR EL FLUJO COMPLETO:"
echo ""
echo "# Una vez que todo esté deployado:"
echo "curl -X POST \"https://lacasadelsueloradiante.es/api/send-reset-email\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\": \"djmartiiservicios@gmail.com\"}'"
echo ""
echo "✅ El email debe llegar con un link a tu dominio"
echo "✅ El link debe abrir tu formulario de reset"
echo "✅ Debe permitir cambiar la contraseña exitosamente"
echo ""

echo "========================================================================="
echo "🎯 RESULTADO ESPERADO"
echo "========================================================================="
echo ""
echo "📧 Email de reset con:"
echo "   • Sujeto: Recupera tu contraseña - La Casa del Suelo Radiante"
echo "   • Link: https://lacasadelsueloradiante.es/auth/reset-password?access_token=xxx"
echo "   • Diseño personalizado (si usas template HTML)"
echo ""
echo "🔗 Al hacer clic:"
echo "   • Abre tu aplicación directamente"
echo "   • Muestra formulario de nueva contraseña"
echo "   • Permite cambio exitoso sin errores"
echo ""

echo "✅ CONFIGURACIÓN COMPLETADA"
echo ""
echo "Los archivos han sido actualizados para asegurar que:"
echo ""
echo "1. resetPasswordForEmail() use el redirectTo correcto"
echo "2. El servidor Supabase tenga las URLs permitidas"
echo "3. El frontend maneje ambos tipos de tokens"
echo ""
echo "🚀 Ahora solo falta implementar en el servidor y probar!"