#!/bin/bash

# ============================================================================
# VERIFICACIÓN COMPLETA DEL redirectTo EN EL FLUJO DE RESET PASSWORD
# ============================================================================

echo "🔗 VERIFICANDO CONFIGURACIÓN DE redirectTo"
echo ""

echo "==========================================================================="
echo "📧 PASO 1: FUNCIÓN DE ENVÍO DE EMAIL (resetPasswordForEmail)"
echo "==========================================================================="
echo ""
echo "📁 Archivo: src/app/api/send-reset-email/route.ts"
echo ""
echo "✅ Configuración actual:"
echo "await supabase.auth.resetPasswordForEmail(email, {"
echo "  redirectTo: 'https://lacasadelsueloradiante.es/auth/reset-password'"
echo "})"
echo ""
echo "🎯 Esto hace que Supabase genere links como:"
echo "https://lacasadelsueloradiante.es/auth/reset-password?access_token=xxx&refresh_token=yyy"
echo ""

echo "==========================================================================="
echo "⚙️ PASO 2: CONFIGURACIÓN EN EL SERVIDOR SUPABASE"
echo "==========================================================================="
echo ""
echo "📁 Archivo en servidor: /root/supabase-automated-self-host/docker/.env"
echo ""
echo "✅ Variables clave que deben coincidir:"
echo ""
echo "SITE_URL=https://lacasadelsueloradiante.es"
echo "MAILER_URLPATHS_RECOVERY=/auth/reset-password"
echo "ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**,https://lacasadelsueloradiante.es/auth/**"
echo ""
echo "🔄 Cómo funciona:"
echo "1. resetPasswordForEmail() respeta el redirectTo del cliente"
echo "2. SITE_URL define el dominio base permitido"
echo "3. ADDITIONAL_REDIRECT_URLS permite las rutas específicas"
echo "4. MAILER_URLPATHS_RECOVERY define la ruta en el template de email"
echo ""

echo "==========================================================================="
echo "🖥️ PASO 3: HANDLER EN EL FRONTEND"
echo "==========================================================================="
echo ""
echo "📁 Archivo: src/app/auth/reset-password/page.tsx"
echo ""
echo "✅ Maneja ambos formatos de tokens:"
echo ""
echo "1. FORMATO MODERNO (access_token + refresh_token):"
echo "   - URL: https://lacasadelsueloradiante.es/auth/reset-password?access_token=xxx&refresh_token=yyy"
echo "   - Flujo: page.tsx → /api/reset-password → supabase.auth.setSession() → updateUser()"
echo ""
echo "2. FORMATO PKCE (token único):"
echo "   - URL: https://lacasadelsueloradiante.es/auth/reset-password?token=xxx&type=recovery"
echo "   - Flujo: page.tsx → supabase.auth.verifyOtp() → updateUser()"
echo ""

echo "==========================================================================="
echo "🧪 PASO 4: PROBAR EL FLUJO COMPLETO"
echo "==========================================================================="
echo ""
echo "1️⃣ Enviar email de reset:"
echo ""
echo "curl -X POST \"http://localhost:3000/api/send-reset-email\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"email\": \"djmartiiservicios@gmail.com\"}'"
echo ""

echo "2️⃣ Verificar que el email llegue con el link correcto:"
echo ""
echo "✅ El email debe contener un link como:"
echo "https://lacasadelsueloradiante.es/auth/reset-password?access_token=xxx&refresh_token=yyy"
echo "o"
echo "https://lacasadelsueloradiante.es/auth/reset-password?token=xxx&type=recovery"
echo ""

echo "3️⃣ Al hacer clic en el link:"
echo ""
echo "✅ Debe abrir: https://lacasadelsueloradiante.es/auth/reset-password"
echo "✅ Debe mostrar el formulario de nueva contraseña"
echo "✅ Debe permitir cambiar la contraseña exitosamente"
echo ""

echo "==========================================================================="
echo "🔧 TROUBLESHOOTING"
echo "==========================================================================="
echo ""
echo "❌ Si el link en el email apunta al dominio de Supabase:"
echo ""
echo "1. Verificar en el servidor VPS:"
echo "   ssh root@servidor"
echo "   cd ~/supabase-automated-self-host/docker"
echo "   grep -E 'SITE_URL|ADDITIONAL_REDIRECT' .env"
echo ""
echo "2. Debe mostrar:"
echo "   SITE_URL=https://lacasadelsueloradiante.es"
echo "   ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**"
echo ""
echo "3. Si no está correcto, editar:"
echo "   nano .env"
echo "   docker-compose restart auth"
echo ""

echo "❌ Si el frontend no puede manejar los tokens:"
echo ""
echo "1. Verificar en los logs del navegador"
echo "2. Verificar que page.tsx maneja ambos formatos de token"
echo "3. Verificar que /api/reset-password funciona"
echo ""

echo "==========================================================================="
echo "📋 RESUMEN DE CONFIGURACIÓN CRÍTICA"
echo "==========================================================================="
echo ""
echo "🎯 Para que redirectTo funcione correctamente:"
echo ""
echo "1. EN EL CLIENTE (resetPasswordForEmail):"
echo "   redirectTo: 'https://lacasadelsueloradiante.es/auth/reset-password'"
echo ""
echo "2. EN EL SERVIDOR (.env de Supabase):"
echo "   SITE_URL=https://lacasadelsueloradiante.es"
echo "   ADDITIONAL_REDIRECT_URLS=https://lacasadelsueloradiante.es/**"
echo ""
echo "3. EN EL FRONTEND (page.tsx):"
echo "   Manejar access_token + refresh_token O token + type"
echo ""
echo "✅ Con esta configuración, el flujo será:"
echo "resetPasswordForEmail() → Email con link correcto → Tu página → Cambio exitoso"
echo ""

echo "🚀 ¿Todo está configurado correctamente? Ejecuta la prueba:"
echo "curl -X POST \"http://localhost:3000/api/send-reset-email\" -H \"Content-Type: application/json\" -d '{\"email\": \"djmartiiservicios@gmail.com\"}'"